config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get '/auth/github', to: 'sessions#create', as: 'github_login'
  get '/auth/github/callback', :to => 'sessions#create'
  # get '/auth/github/callback', to: 'sessions#create', as: "github_login"
  delete '/logout', to:'sessions#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person

  def initialize()
end

app/models/user.rb
class User < ActiveRecord::Base
  def self.from_omniauth(auth_info)
    where(uid: auth_info[:uid]).first_or_create do |new_user|
      new_user.uid = auth_info.uid
      new_user.name = auth_info.extra.raw_info.name
      new_user.nickname = auth_info.extra.raw_info.nickname
      new_user.oauth_token = auth_info.credentials.token
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    conn = Faraday.new(url: "https://api.github.com") do |faraday|
      faraday.adapter Faraday.default_adapter
    end
    conn.headers["Authorization"] = "token #{User.first.oauth_token}"
    response = conn.get("/user")
    @person = JSON.parse(response.body)
  end
end

# "Authorization: token OAUTH-TOKEN"
# 'https://api.github.com'

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    if user = User.from_omniauth(request.env["omniauth.auth"])
      session[:user_id] = user.id
    end
    redirect_to root_path
  end

  def destroy
    reset_session
    redirect_to root_url, notice: "Signed out!"
  end

  protected

  def auth_hash
    request.env["omniauth.auth"].inspect
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/home/index.html.erb
<h1>Home</h1>

<%= @person["email"] %>
<%= link_to "repos", @person["repos_url"] %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PersonalOauth</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user %>
      Hello, <%= current_user.name %>
      <%= link_to "Logout", logout_path, method: :delete %>
    <% else %>
      <%= link_to "Sign in with Github", github_login_path %>
    <% end %>
    <%= yield %>
  </body>
</html>